// webapp/src/lib/components/from-to-table.tsx
import { clsx } from "clsx";
import { Index, type JSX, Show } from "solid-js";
import Avatar from "@/lib/components/avatar";
import CurrencyEuro from "@/lib/components/icons/currency-euro";
import Trash from "@/lib/components/icons/trash";

interface Item {
  amount: number;
  from: string;
  to: string;
}

interface Props {
  accent?: string;
  children?: JSX.Element;
  emptyMessage?: string;
  items: Item[];
  onfocus?: () => void;
  onItemsChange: (items: Item[]) => void;
  onRemove?: (index: number) => void;
}

export default function FromToTable(props: Props) {
  function updateField(i: number, field: keyof Item, value: string | number) {
    props.onItemsChange(
      props.items.map((item, j) =>
        j === i ? { ...item, [field]: value } : item
      )
    );
  }

  function updateAmount(i: number, raw: string) {
    const v = Number.parseFloat(raw);
    if (!Number.isNaN(v)) {
      updateField(i, "amount", Math.round(v * 100));
    }
  }

  return (
    <>
      <Show when={props.items.length > 0}>
        <div class="overflow-x-auto rounded-xl border border-slate-700/60">
          <table class="w-full">
            <thead>
              <tr class="border-slate-700/60 border-b bg-slate-800/60">
                <th class="px-4 py-3 text-left font-semibold text-slate-400 text-xs uppercase tracking-wider">
                  From
                </th>
                <th class="px-4 py-3 text-left font-semibold text-slate-400 text-xs uppercase tracking-wider">
                  To
                </th>
                <th class="px-4 py-3 text-left font-semibold text-slate-400 text-xs uppercase tracking-wider">
                  Amount
                </th>
                <th class="px-4 py-3 text-right" />
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-800">
              <Index each={props.items}>
                {(item, i) => (
                  <tr class="transition-colors duration-150 hover:bg-slate-800/40">
                    <td class="px-4 py-3">
                      <div class="flex items-center gap-2.5">
                        <Avatar name={item().from} />
                        <input
                          class={clsx(
                            "min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-800/60 px-2.5 py-1.5 text-slate-200 text-sm transition-all duration-200 max-sm:max-w-20 sm:w-24",
                            props.accent === "emerald"
                              ? "focus:border-emerald-500 focus:outline-none focus:ring-2 focus:ring-emerald-500/30"
                              : "focus:border-violet-500 focus:outline-none focus:ring-2 focus:ring-violet-500/30"
                          )}
                          onFocus={props.onfocus}
                          onInput={(e) =>
                            updateField(i, "from", e.currentTarget.value)
                          }
                          type="text"
                          value={item().from}
                        />
                      </div>
                    </td>
                    <td class="px-4 py-3">
                      <div class="flex items-center gap-2.5">
                        <Avatar name={item().to} />
                        <input
                          class={clsx(
                            "min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-800/60 px-2.5 py-1.5 text-slate-200 text-sm transition-all duration-200 max-sm:max-w-20 sm:w-24",
                            props.accent === "emerald"
                              ? "focus:border-emerald-500 focus:outline-none focus:ring-2 focus:ring-emerald-500/30"
                              : "focus:border-violet-500 focus:outline-none focus:ring-2 focus:ring-violet-500/30"
                          )}
                          onFocus={props.onfocus}
                          onInput={(e) =>
                            updateField(i, "to", e.currentTarget.value)
                          }
                          type="text"
                          value={item().to}
                        />
                      </div>
                    </td>
                    <td class="px-4 py-3">
                      <div class="relative inline-block">
                        <span class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-2.5">
                          <CurrencyEuro class="size-3.5 translate-y-px text-slate-600" />
                        </span>
                        <input
                          class={clsx(
                            "min-w-0 rounded-lg border border-slate-700 bg-slate-800/60 py-1.5 pr-2.5 pl-8 font-medium text-slate-200 text-sm transition-all duration-200 max-sm:w-24 sm:w-28",
                            props.accent === "emerald"
                              ? "focus:border-emerald-500 focus:outline-none focus:ring-2 focus:ring-emerald-500/30"
                              : "focus:border-violet-500 focus:outline-none focus:ring-2 focus:ring-violet-500/30"
                          )}
                          onFocus={props.onfocus}
                          onInput={(e) =>
                            updateAmount(i, e.currentTarget.value)
                          }
                          step="0.01"
                          type="number"
                          value={item().amount / 100}
                        />
                      </div>
                    </td>
                    <td class="px-4 py-3 text-right">
                      <button
                        aria-label="Remove row"
                        class="rounded-lg p-2.5 text-slate-600 transition-all duration-200 hover:bg-red-500/15 hover:text-red-400 active:bg-red-500/25"
                        onClick={() => props.onRemove?.(i)}
                        type="button"
                      >
                        <Trash />
                      </button>
                    </td>
                  </tr>
                )}
              </Index>
            </tbody>
          </table>
        </div>
      </Show>
      <Show when={props.items.length === 0 && props.children}>
        <div class="flex flex-col items-center justify-center py-10 text-center">
          <div class="mb-3 flex size-14 items-center justify-center rounded-2xl bg-slate-800/60 ring-1 ring-slate-700/50">
            {props.children}
          </div>
          <p class="text-slate-500 text-sm">
            {props.emptyMessage ?? "No items yet"}
          </p>
        </div>
      </Show>
    </>
  );
}

// webapp/src/lib/components/from-to-table.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import Avatar from "./avatar.svelte";

  interface Item {
    amount: number;
    from: string;
    to: string;
  }

  import CurrencyEuro from "$lib/components/icons/currency-euro.svelte";
  import Trash from "$lib/components/icons/trash.svelte";

  const focusRings: Record<string, string> = {
    violet:
      "focus:border-violet-500 focus:outline-none focus:ring-2 focus:ring-violet-500/30",
    emerald:
      "focus:border-emerald-500 focus:outline-none focus:ring-2 focus:ring-emerald-500/30",
  };

  let {
    items = $bindable(),
    accent = "violet",
    onfocus,
    onremove,
    empty,
    emptyMessage = "No items yet",
  }: {
    items: Item[];
    accent?: string;
    onfocus?: () => void;
    onremove?: (index: number) => void;
    empty?: Snippet;
    emptyMessage?: string;
  } = $props();

  const focusRing = $derived(focusRings[accent] ?? focusRings.violet);
</script>

{#if items.length > 0}
  <div class="overflow-x-auto rounded-xl border border-slate-700/60">
    <table class="w-full">
      <thead>
        <tr class="border-b border-slate-700/60 bg-slate-800/60">
          <th
            class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-400"
          >
            From
          </th>
          <th
            class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-400"
          >
            To
          </th>
          <th
            class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-400"
          >
            Amount
          </th>
          <th class="px-4 py-3 text-right"></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-slate-800">
        {#each items as _, i}
          <tr class="transition-colors duration-150">
            <td class="px-4 py-3">
              <div class="flex items-center gap-2.5">
                <Avatar name={items[i].from} />
                <input
                  type="text"
                  bind:value={items[i].from}
                  {onfocus}
                  class="min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-800/60 px-2.5 py-1.5 text-sm text-slate-200 transition-all duration-200 max-sm:max-w-20 sm:w-24 {focusRing}"
                >
              </div>
            </td>
            <td class="px-4 py-3">
              <div class="flex items-center gap-2.5">
                <Avatar name={items[i].to} />
                <input
                  type="text"
                  bind:value={items[i].to}
                  {onfocus}
                  class="min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-800/60 px-2.5 py-1.5 text-sm text-slate-200 transition-all duration-200 max-sm:max-w-20 sm:w-24 {focusRing}"
                >
              </div>
            </td>
            <td class="px-4 py-3">
              <div class="relative inline-block">
                <span
                  class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-2.5"
                >
                  <CurrencyEuro
                    class="size-3.5 translate-y-px text-slate-600"
                  />
                </span>
                <input
                  type="number"
                  step="0.01"
                  value={items[i].amount / 100}
                  oninput={(e) => {
                      const v = Number.parseFloat(e.currentTarget.value);
                      if (!Number.isNaN(v)) { items[i].amount = Math.round(v * 100); }
                    }}
                  {onfocus}
                  class="min-w-0 rounded-lg border border-slate-700 bg-slate-800/60 py-1.5 pl-8 pr-2.5 text-sm font-medium text-slate-200 transition-all duration-200 max-sm:w-24 sm:w-28 {focusRing}"
                >
              </div>
            </td>
            <td class="px-4 py-3 text-right">
              <button
                type="button"
                onclick={() => onremove?.(i)}
                aria-label="Remove row"
                class="rounded-lg p-2.5 text-slate-600 transition-all duration-200 hover:bg-red-500/15 hover:text-red-400 active:bg-red-500/25"
              >
                <Trash />
              </button>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{:else if empty}
  <div class="flex flex-col items-center justify-center py-10 text-center">
    <div
      class="mb-3 flex size-14 items-center justify-center rounded-2xl bg-slate-800/60 ring-1 ring-slate-700/50"
    >
      {@render empty()}
    </div>
    <p class="text-sm text-slate-500">{emptyMessage}</p>
  </div>
{/if}

<style>
  @media (hover: hover) {
    tbody tr:hover {
      background-color: rgba(30, 41, 59, 0.4);
    }
  }
</style>
