// webapp/src/lib/components/balance-table.tsx
import { clsx } from "clsx";
import { Index, type JSX, Show } from "solid-js";
import Avatar from "@/lib/components/avatar";
import CurrencyEuro from "@/lib/components/icons/currency-euro";
import Trash from "@/lib/components/icons/trash";
import type { Balance } from "@/lib/types";

interface Props {
  children?: JSX.Element;
  emptyMessage?: string;
  items: Balance[];
  onfocus?: () => void;
  onItemsChange: (items: Balance[]) => void;
  onRemove?: (index: number) => void;
}

function statusLabel(amount: number): string {
  if (amount < 0) {
    return "owes";
  }
  if (amount > 0) {
    return "owed";
  }
  return "settled";
}

export default function BalanceTable(props: Props) {
  function updateField(
    i: number,
    field: keyof Balance,
    value: string | number
  ) {
    props.onItemsChange(
      props.items.map((item, j) =>
        j === i ? { ...item, [field]: value } : item
      )
    );
  }

  function updateAmount(i: number, raw: string) {
    const v = Number.parseFloat(raw);
    if (!Number.isNaN(v)) {
      updateField(i, "amount", Math.round(v * 100));
    }
  }

  return (
    <>
      <Show when={props.items.length > 0}>
        <div class="overflow-x-auto rounded-xl border border-slate-700/60">
          <table class="w-full">
            <thead>
              <tr class="border-slate-700/60 border-b bg-slate-800/60">
                <th class="px-4 py-3 text-left font-semibold text-slate-400 text-xs uppercase tracking-wider">
                  Person
                </th>
                <th class="px-4 py-3 text-left font-semibold text-slate-400 text-xs uppercase tracking-wider">
                  Balance
                </th>
                <th class="px-4 py-3 text-right" />
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-800">
              <Index each={props.items}>
                {(item, i) => (
                  <tr class="transition-colors duration-150 hover:bg-slate-800/40">
                    <td class="px-4 py-3.5">
                      <div class="flex items-center gap-2.5">
                        <Avatar name={item().person} />
                        <input
                          class="min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-800/60 px-2.5 py-1.5 text-slate-200 text-sm transition-all duration-200 focus:border-amber-500 focus:outline-none focus:ring-2 focus:ring-amber-500/30 max-sm:max-w-20 sm:w-24"
                          onFocus={props.onfocus}
                          onInput={(e) =>
                            updateField(i, "person", e.currentTarget.value)
                          }
                          type="text"
                          value={item().person}
                        />
                      </div>
                    </td>
                    <td class="px-4 py-3.5">
                      <div class="flex items-center gap-2">
                        <div class="relative inline-block">
                          <span class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-2.5">
                            <CurrencyEuro class="size-3.5 translate-y-px text-slate-600" />
                          </span>
                          <input
                            class={clsx(
                              "min-w-0 rounded-lg border border-slate-700 bg-slate-800/60 py-1.5 pr-2.5 pl-8 font-medium font-mono text-sm transition-all duration-200 focus:border-amber-500 focus:outline-none focus:ring-2 focus:ring-amber-500/30 max-sm:w-24 sm:w-28",
                              item().amount < 0 && "text-red-400",
                              item().amount > 0 && "text-emerald-400",
                              item().amount === 0 && "text-slate-400"
                            )}
                            onFocus={props.onfocus}
                            onInput={(e) =>
                              updateAmount(i, e.currentTarget.value)
                            }
                            step="0.01"
                            type="number"
                            value={item().amount / 100}
                          />
                        </div>
                        <span
                          class={clsx(
                            "font-medium text-xs",
                            item().amount < 0 && "text-red-400",
                            item().amount > 0 && "text-emerald-400",
                            item().amount === 0 && "text-slate-500"
                          )}
                        >
                          {statusLabel(item().amount)}
                        </span>
                      </div>
                    </td>
                    <td class="px-4 py-3.5 text-right">
                      <button
                        aria-label="Remove balance"
                        class="rounded-lg p-2.5 text-slate-600 transition-all duration-200 hover:bg-red-500/15 hover:text-red-400 active:bg-red-500/25"
                        onClick={() => props.onRemove?.(i)}
                        type="button"
                      >
                        <Trash />
                      </button>
                    </td>
                  </tr>
                )}
              </Index>
            </tbody>
          </table>
        </div>
      </Show>
      <Show when={props.items.length === 0 && props.children}>
        <div class="flex flex-col items-center justify-center py-10 text-center">
          <div class="mb-3 flex size-14 items-center justify-center rounded-2xl bg-slate-800/60 ring-1 ring-slate-700/50">
            {props.children}
          </div>
          <p class="text-slate-500 text-sm">
            {props.emptyMessage ?? "No items yet"}
          </p>
        </div>
      </Show>
    </>
  );
}

// frontend/src/lib/components/BalanceTable.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import CurrencyEuro from "$lib/components/icons/CurrencyEuro.svelte";
  import Trash from "$lib/components/icons/Trash.svelte";
  import type { Balance } from "$lib/types";
  import Avatar from "./Avatar.svelte";

  let {
    items = $bindable(),
    accent = "amber",
    onfocus = () => {},
    onremove,
    empty,
    emptyMessage = "No items yet",
  }: {
    items: Balance[];
    accent?: string;
    onfocus?: () => void;
    onremove?: (index: number) => void;
    empty?: Snippet;
    emptyMessage?: string;
  } = $props();
</script>

{#if items.length > 0}
  <div class="overflow-hidden rounded-xl border border-slate-700/60">
    <table class="w-full">
      <thead>
        <tr class="border-b border-slate-700/60 bg-slate-800/60">
          <th
            class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-400"
          >
            Person
          </th>
          <th
            class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-400"
          >
            Balance
          </th>
          <th class="px-4 py-3 text-right"></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-slate-800">
        {#each items as _, i}
          <tr class="transition-colors duration-150 hover:bg-slate-800/40">
            <td class="px-4 py-3.5">
              <div class="flex items-center gap-2.5">
                <Avatar name={items[i].person} />
                <input
                  type="text"
                  bind:value={items[i].person}
                  {onfocus}
                  class="w-24 rounded-lg border border-slate-700 bg-slate-800/60 px-2.5 py-1.5 text-sm text-slate-200 transition-all duration-200 focus:border-amber-500 focus:outline-none focus:ring-2 focus:ring-amber-500/30"
                >
              </div>
            </td>
            <td class="px-4 py-3.5">
              <div class="flex items-center gap-2">
                <div class="relative inline-block">
                  <span
                    class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-2.5"
                  >
                    <CurrencyEuro
                      class="size-3.5 translate-y-px text-slate-600"
                    />
                  </span>
                  <input
                    type="number"
                    step="0.01"
                    value={items[i].amount / 100}
                    oninput={(e) => {
                      const v = parseFloat(e.currentTarget.value);
                      if (!Number.isNaN(v)) items[i].amount = Math.round(v * 100);
                    }}
                    {onfocus}
                    class={[
                      "w-28 rounded-lg border border-slate-700 bg-slate-800/60 py-1.5 pl-8 pr-2.5 text-sm font-mono font-medium transition-all duration-200 focus:border-amber-500 focus:outline-none focus:ring-2 focus:ring-amber-500/30",
                      items[i].amount < 0 && "text-red-400",
                      items[i].amount > 0 && "text-emerald-400",
                      items[i].amount === 0 && "text-slate-400",
                    ]}
                  >
                </div>
                <span
                  class={[
                  "text-xs font-medium",
                  items[i].amount < 0 && "text-red-400",
                  items[i].amount > 0 && "text-emerald-400",
                  items[i].amount === 0 && "text-slate-500",
                ]}
                >
                  {items[i].amount < 0 ? "owes" : items[i].amount > 0 ? "owed" : "settled"}
                </span>
              </div>
            </td>
            <td class="px-4 py-3.5 text-right">
              <button
                onclick={() => onremove?.(i)}
                aria-label="Remove balance"
                class="rounded-lg p-1.5 text-slate-600 transition-all duration-200 hover:bg-red-500/15 hover:text-red-400"
              >
                <Trash />
              </button>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{:else if empty}
  <div class="flex flex-col items-center justify-center py-10 text-center">
    <div
      class="mb-3 flex size-14 items-center justify-center rounded-2xl bg-slate-800/60 ring-1 ring-slate-700/50"
    >
      {@render empty()}
    </div>
    <p class="text-sm text-slate-500">{emptyMessage}</p>
  </div>
{/if}
