// webapp/src/lib/components/empty-state.tsx
import { type Element, Show } from "solid-js";
import CurrencyEuro from "@/lib/components/icons/currency-euro";

interface Props {
  children?: Element;
  message: string;
}

export default function EmptyState(props: Props) {
  return (
    <div class="flex flex-col items-center justify-center py-10 text-center">
      <div class="mb-3 flex size-14 items-center justify-center rounded-2xl bg-slate-800/60 ring-1 ring-slate-700/50">
        <Show
          fallback={<CurrencyEuro class="size-7 text-slate-600" />}
          when={props.children}
        >
          {props.children}
        </Show>
      </div>
      <p class="text-slate-500 text-sm">{props.message}</p>
    </div>
  );
}

// frontend/src/lib/components/EmptyState.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  import CurrencyEuro from "$lib/components/icons/CurrencyEuro.svelte";

  let { message, children }: { message: string; children?: Snippet } = $props();
</script>

<div class="flex flex-col items-center justify-center py-10 text-center">
  <div
    class="mb-3 flex size-14 items-center justify-center rounded-2xl bg-slate-800/60 ring-1 ring-slate-700/50"
  >
    {#if children}
      {@render children()}
    {:else}
      <CurrencyEuro class="size-7 text-slate-600" />
    {/if}
  </div>
  <p class="text-sm text-slate-500">{message}</p>
</div>
